/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.dmitrix.wallet.api;

import com.dmitrix.wallet.api.model.ErrorResponse;
import java.util.UUID;
import com.dmitrix.wallet.api.model.WalletRequest;
import com.dmitrix.wallet.api.model.WalletResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-22T12:08:02.859144900+03:00[Europe/Moscow]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Wallet", description = "the Wallet API")
public interface WalletApi {

    /**
     * GET /api/v1/wallets/{id} : get wallet by id
     *
     * @param id  (required)
     * @return Ok (status code 200)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "getWalletById",
        summary = "get wallet by id",
        tags = { "Wallet" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WalletResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/v1/wallets/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<WalletResponse> getWalletById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") UUID id
    );


    /**
     * POST /api/v1/wallet : Update wallet
     *
     * @param walletRequest  (required)
     * @return Ok (status code 200)
     *         or Validation error (status code 400)
     *         or Not found (status code 404)
     *         or Not enough money (status code 422)
     */
    @Operation(
        operationId = "updateWallet",
        summary = "Update wallet",
        tags = { "Wallet" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WalletResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Validation error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "422", description = "Not enough money", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/wallet",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<WalletResponse> updateWallet(
        @Parameter(name = "WalletRequest", description = "", required = true) @Valid @RequestBody WalletRequest walletRequest
    );

}
